### ISSUE TITLE
pulling ads information

### ISSUE THREAD

**Issue by jeffreydinh** [facebook/facebook-nodejs-ads-sdk#1]
I'm trying to pull ads info/insight on an account but am confused how it works. I'm using the code below,:

account
  .read([AdAccount.Fields.name])
  .then((account) => {
    // logPassedTest(test1 + ':Pass', account);
    console.log(`account: ${JSON.stringify(account)}`)
  })
  .catch((error) => {
  	console.log(`error: ${error}`)
  });

// this returns the below format, data is omitted.

{
	"_data": {
		"id": "",
		"name": ""
	},
	"_fields": [],
	"_changes": {},
	"id": "",
	"name": "",
	"_api": {
		"accessToken": "",
		"locale": "en_US",
		"_debug": false
	}
}

How do i pull info on the fields returned, since just an array of field name returns? How can I get the values from these field names? How can I pull general analytics data on the Ads Account?

**Comment by zanyaziz** [comment]
Try this example below. Note that only the fields you specified in the read fields param are the ones that will be populated in the $account response.

const adsSdk = require('facebook-nodejs-ads-sdk');
const accessToken = '<ACCESS_TOKEN>';
const accountId = 'act_<ACCOUNT_ID>';
const FacebookAdsApi = adsSdk.FacebookAdsApi.init(accessToken);
FacebookAdsApi.setDebug(true);
const AdAccount = require('facebook-nodejs-ads-sdk').AdAccount;
const account = new AdAccount(accountId);

console.log(account.id) // fields can be accessed as properties
account
  .read([AdAccount.Fields.name, AdAccount.Fields.age])
  .then((account) => {
    console.log(account);
  })
  .catch((error) => {
    console.log('An error occurred');
  });

**Comment by jeffreydinh** [comment]
I'm getting this error when I ran the code you provided:

An error occurred: FacebookRequestError: (#100) Tried accessing nonexisting field (age) on node type (Application)

It seems to not work when I add more than one field to the array. I tried with these fields as well:

const adsSdk = require('facebook-nodejs-ads-sdk');
const FacebookAdsApi = adsSdk.FacebookAdsApi.init(accessToken);
FacebookAdsApi.setDebug(true);
const AdAccount = require('facebook-nodejs-ads-sdk').AdAccount;
const account = new AdAccount(accountId);

console.log(account.id) // fields can be accessed as properties
account
.read([AdAccount.Fields.name, AdAccount.Fields.balances])
.then((account) => {
console.log(`account: ${account.account_id}`);
})
.catch((error) => {
console.log(`An error occurred: ${error}`);
});

And it gives a different error than the age field: 

An error occurred: FacebookRequestError: Syntax error "Expected name." at character 5: name,

**Comment by zanyaziz** [comment]
Here's how you can do what you're trying to achieve. 


const adsSdk = require('facebook-nodejs-ads-sdk');
const accessToken = '<Access_Token>';
const accountId = 'act_<Account_ID>';
const FacebookAdsApi = adsSdk.FacebookAdsApi.init(accessToken);
FacebookAdsApi.setDebug(true);
const AdAccount = require('facebook-nodejs-ads-sdk').AdAccount;
const account = new AdAccount(accountId);

account
  .read([AdAccount.Fields.name, AdAccount.Fields.age])
  .then((account) => {
    console.log(account.name);
    console.log(account.age);
  })
  .catch((error) => {
    console.log('An error occurred');
    console.lof(error);
  });

account
  .read([AdAccount.Fields.age])
  .then((account) => {
    console.log(account.age);
  })
  .catch((error) => {
    console.log('An error occurred');
    console.log(error);
  });

**Comment by zanyaziz** [comment]
Did that resolve your issue?

**Comment by jeffreydinh** [comment]
This did not resolve my issue. I'm still getting the same errors

**Comment by zanyaziz** [comment]
I looked into the issue. It seems like this may be an intermittent issue with the APIs and not the SDK. Can you file a bug at https://developers.facebook.com/bugs/
