### ISSUE TITLE
How to POST to /client_pages

### ISSUE THREAD

**Issue by j-jackson** [facebook/facebook-nodejs-ads-sdk#10]
This is probably a stupid question, but I cant figure out how to `POST` to `"https://graph.facebook.com/<API_VERSION>/<BUSINESS_ID>/client_pages"`

I can see [getClientPages()](https://github.com/facebook/facebook-nodejs-ads-sdk/blob/0e473eec798763204f9e5e765ca6235fe4ed032a/src/objects/business.js#L96) which works but is it possible to post to /`client_pages`?

Example: https://developers.facebook.com/docs/marketing-api/businessmanager/assets#pages

**Comment by zanyaziz** [comment]
No there isn't a way to do that.
