### ISSUE TITLE
Token Refresh

### ISSUE THREAD

**Issue by dangsd** [facebook/facebook-nodejs-ads-sdk#11]
Hi, is there a way to refresh access token here? or it is auto managed by the sdk given the first initial access token? thanks!

**Comment by zanyaziz** [comment]
It is not auto managed. You can either get a long lived access token or a system user with an access token to use in the SDK. Here's more info that you may find useful.

https://developers.facebook.com/docs/marketing-api/businessmanager/systemuser
https://developers.facebook.com/docs/facebook-login/access-tokens/expiration-and-extension/
