### ISSUE TITLE
Business.getAssignedPages only returns id not a request field

### ISSUE THREAD

**Issue by roundrobin** [facebook/facebook-nodejs-ads-sdk#2]
Hey,

I'm trying to request all pages of an ad account, but this method call only returns the page id and not the corresponding name.

Any help here?

```
new Business(BUSINESS_ID).getAssignedPages([
        Business.Fields.name
    ], {}, true).then((result)=>{
    //console.log("....", result);
    if(result){
        result.forEach((page)=>{
            console.log("getAssignedPages", "----------------->", page);
        })
    }
}).catch((err)=>{

});```

**Comment by zanyaziz** [comment]
Hi roundrobin, 
Can you download the latest version of the sdk package? There was a bug that needed to be fixed which should resolve your issue. Keep me posted on if that fixed your issue.

**Comment by roundrobin** [comment]
Yes the new version fixed the issue,

**Comment by zanyaziz** [comment]
Thanks
