### ISSUE TITLE
Code with problems on README.md

### ISSUE THREAD

**Issue by bertero** [facebook/facebook-nodejs-ads-sdk#40]
Hey guys,

Sorry to bother with this, however I code in JS (node, react, angular, etc) and I have never seen the way you write code before.

That said, I am having some issues with the tutorial code on the README.md file. I would really appreciate if you could explain it to me.

I am trying to read some campaign and account objects, but I have some doubts here:

 ```javascript
const adsSdk = require('facebook-nodejs-ads-sdk');
const accessToken = '<VALID_ACCESS_TOKEN>';
const api = adsSdk.FacebookAdsApi.init(accessToken);
const AdAccount = adsSdk.AdAccount;
const account = new AdAccount('act_<AD_ACCOUNT_ID>');
account
  .read([AdAccount.Fields.name, AdAccount.Fields.age])
  .then((account) => {
    logPassedTest(test1 + ':Pass', account);
  })
  .catch((error) => {
  });
```

1) Where is `logPassedTest` defined?
2) Where is `test1` defined and used before logging?
3) How can I iterate over all campaigns of one ad_account?

Thanks!

**Comment by vicdus** [comment]
This piece of code comes from [https://github.com/facebook/facebook-nodejs-ads-sdk/blob/master/examples/BasicExample.js](url) and `logPassedTest`, `test1` are defined there. We will fix the document in Readme.md soon to make it more clear.

About pagination, you may see this example.

```
const adsSdk = require('facebook-nodejs-ads-sdk');
const accessToken = '<VALID_ACCESS_TOKEN>';
const api = adsSdk.FacebookAdsApi.init(accessToken);
const AdAccount = adsSdk.AdAccount;
const account = new AdAccount('act_<AD_ACCOUNT_ID>');

void async function () {
    let campaigns = await account.getCampaigns([Campaign.Fields.name], {limit: 20});
    campaigns.forEach(c => console.log(c.name));
    while (campaigns.hasNext()) {
        campaigns = await campaigns.next();
        campaigns.forEach(c => console.log(c.name));
    }
}();
```

If your NodeJS version support async/await.

**Comment by bertero** [comment]
Thank you so much!

The code in `BasicExample.js` is crystal clear!

I also appreciate the example you sent above, it's very easy.

You should update the README.md indeed. Or at least indicate the example's path.
