### ISSUE TITLE
Add support for v2.10

### ISSUE THREAD

**Issue by Ivkaa** [facebook/facebook-nodejs-ads-sdk#6]
I have created a new application and I cannot use older version of the API. This is the error I get:
```
{ error:
  {
     message: '(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v2.10.',
     type: 'OAuthException',
     code: 2635,
     fbtrace_id: 'HcmbKfHlScm' 
  }
},
```

**Comment by josescasanova** [comment]
I went ahead and created a pull request for this: https://github.com/facebook/facebook-nodejs-ads-sdk/pull/7

**Comment by zanyaziz** [comment]
Added support for both v2.10 and v2.11 (Latest)
